#  Options: install/uninstall/check
#
#  Install:   ansible-playbook   oracle-java8.yaml --tags=install
#  Uninstall: ansible-playbook   oracle-java8.yaml --tags=uninstall
#  Check:     ansible-playbook -v  oracle-java8.yaml --tags=check
#                             ====

---

- hosts: localhost
  connection: local
  become: true
  vars:
    JDK:
      Install_Path: '/opt/'
      Ver: 'jdk1.8.0_251'

  tasks:
  - name: Install Oracle Java
    block:
    - name: Extract archive
      unarchive:
        src:  "{{JDK['Ver'] + '.tar.gz'}}"
        dest: "{{JDK['Install_Path']}}"
        extra_opts: --no-same-owner

    - name: Create a symbolic link
      file:
        src: "{{JDK['Install_Path'] + JDK['Ver']}}/bin/java"
        dest: '/usr/bin/java'
        owner: root
        group: root
        state: link
    tags: 
      - install

  - block:
    - name: Uninstall Oracle Java
      file: 
        path: '{{ item }}'
        state: absent
      with_items:
        - "{{JDK['Install_Path'] + JDK['Ver']}}"
        - "/usr/bin/java"
    tags: 
      - uninstall

  - name: Check Java
    block:
    - name: 'Linux distro:'
      debug: msg="{{ansible_distribution}}"
    - name: 'Java version:'
      command: /usr/bin/java -version
      register: jdkver
    - debug: msg="{{jdkver.stderr}}"
    tags:
      - check

